name: Build
on:
  push:
    paths:
    - '.codecov.yml'
    - '.github/workflows/build.yml'
    - 'CMakeLists.txt'
    - 'examples/**'
    - 'include/**'
    - 'Makefile'
    - 'src/**'
    - 'tests/**'

jobs:
  Unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
        - os: ubuntu-latest
          OS_TAG: Linux
          BUILD_OPTS: -DCMAKE_BUILD_TYPE=Debug -DPUMAS_BUILD_TEST=true -DPUMAS_USE_GDB=true
        - os: macos-latest
          OS_TAG: OSX
          BUILD_OPTS: -DCMAKE_INSTALL_PREFIX=$(pwd)/.. -DPUMAS_BUILD_EXAMPLES=true

    steps:
    - uses: actions/checkout@v2

    - if: matrix.OS_TAG == 'Linux'
      name: Install lcov
      run: |
        sudo apt-get install -y lcov

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ${{ matrix.BUILD_OPTS }} ..
        make

    - if: matrix.OS_TAG == 'Linux'
      name: Test
      run: |
        cd build
        make coverage

    - if: matrix.OS_TAG == 'Linux'
      name: Coverage
      uses: codecov/codecov-action@v1

    - if: matrix.OS_TAG == 'OSX'
      name: Install
      run: |
        cd build
        make install

    - if: matrix.OS_TAG == 'OSX'
      name: Examples
      run: |
        ./bin/example-tabulate
        ./bin/example-dump
        ./bin/example-loader
        ./bin/example-geometry 10 10 1
        ./bin/example-straight 10 10 1
